### ISSUE TITLE
Variable reference 'makeStatePath' is unbound ! 

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [sifive/api-scala-sifive#18]
when we are running the command in block-pio-sifive repository, for  creating an onboarding document following error is coming , which we came to know that, it is from this api-scala-sifive repository:
<pre><font color="#8AE234"><b>shraddha@terminal</b></font>:<font color="#729FCF"><b>~/pio</b></font>$ wake makeOnboardingDocument pioDUT
Variable reference &apos;makeStatePath&apos; is unbound at api-scala-sifive/scala.wake:19:[16-28]
&gt;&gt;&gt; Aborting without execution &lt;&lt;&lt;</pre>

So, what can we do to resolve this?

**Comment by jackkoenig** [comment]
This error shows up if you're building wake from master, you should use the latest stable version, 0.17.1: https://github.com/sifive/wake/releases/tag/v0.17.1
